/*
Copyright (C) 2026  richardaburton@gmail.com 

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program.  If not, see <http://www.gnu.org/licenses/>.
*/

#include "vmlinux.h" // generated by Makefile
#include <bpf/bpf_helpers.h>
#include <bpf/bpf_core_read.h>
#include <bpf/bpf_tracing.h>

#include "provisioner.h"

char LICENSE[] SEC("license") = "GPL";

// user-space configured interface name
const volatile char target_ifname[16] = "wg1";

// shadows definitions for co-re
struct noise_handshake {
    unsigned char remote_static[32];
} __attribute__((preserve_access_index));

struct wg_device {
    struct net_device *dev;
} __attribute__((preserve_access_index));

struct wg_peer {
    struct wg_device *device;
    struct noise_handshake handshake;
} __attribute__((preserve_access_index));

struct index_hashtable_entry {
    struct wg_peer *peer;
} __attribute__((preserve_access_index));

struct noise_keypair {
    struct index_hashtable_entry entry;
} __attribute__((preserve_access_index));

struct packet_cb {
    struct noise_keypair *keypair;
} __attribute__((preserve_access_index));


// map to track seen ips and their last seen time
// pinned so remains if userspace dies
struct {
    __uint(type, BPF_MAP_TYPE_HASH);
    __uint(max_entries, 1048576);
    __type(key, unsigned __int128);
    __type(value, struct record_t);
    __uint(pinning, LIBBPF_PIN_BY_NAME);
} ip_ledger SEC(".maps");

// option dos protection
#ifdef ENABLE_DOS_PROTECTION
struct {
    __uint(type, BPF_MAP_TYPE_HASH);
    __uint(max_entries, 8192);
    __type(key, struct pk_wrap);
    __type(value, struct peer_quota);
} map_peer_quotas SEC(".maps");
#endif

struct {
    __uint(type, BPF_MAP_TYPE_PERCPU_ARRAY);
    __uint(max_entries, 1);
    __type(key, __u32);
    __type(value, struct scratch_pad);
} scratch_map SEC(".maps");

struct {
    __uint(type, BPF_MAP_TYPE_PERF_EVENT_ARRAY);
    __uint(key_size, sizeof(__u32));
    __uint(value_size, sizeof(__u32));
} events SEC(".maps");


SEC("kprobe/wg_allowedips_lookup_src")
int BPF_KPROBE(handler_lookup_src, void *table, struct sk_buff *skb)
{
    if (!skb) return 0;

    // check interface name matches target
    struct net_device *net_dev = BPF_CORE_READ(skb, dev);
    if (!net_dev) return 0;
    char ifname[16];
    bpf_core_read_str(ifname, sizeof(ifname), &net_dev->name);
    #pragma unroll
    for (int i = 0; i < 16; i++) {
        if (ifname[i] != target_ifname[i]) return 0;
        if (target_ifname[i] == '\0') break;
    }

    // check this is an ipv6 packet and read the source address
    unsigned __int128 saddr;
    unsigned char *head = BPF_CORE_READ(skb, head);
    u16 net_header = BPF_CORE_READ(skb, network_header);
    struct ipv6hdr *ip6h = (struct ipv6hdr *)(head + net_header);
    
    __u8 version_byte;
    if (bpf_probe_read_kernel(&version_byte, 1, ip6h) < 0) return 0;
    if ((version_byte >> 4) != 6) return 0;

    if (bpf_probe_read_kernel(&saddr, sizeof(saddr), &ip6h->saddr) < 0) return 0;

    // already a known ip?
    struct record_t *rec = bpf_map_lookup_elem(&ip_ledger, &saddr);
    __u64 now = bpf_ktime_get_ns();
    if (rec) {
        // update last seen time
        rec->last_seen = now;
        return 0;
    }

    // else, new ip to be learned
    __u32 zero = 0;
    struct scratch_pad *scratch = bpf_map_lookup_elem(&scratch_map, &zero);
    if (!scratch) return 0;

    // follow the skb->cb -> noise_keypair -> index_hashtable_entry -> wg_peer chain
    struct packet_cb *cb = (struct packet_cb *)skb->cb;
    if (!cb) return 0;
    
    // follow the chain: packet_cb -> noise_keypair -> index_hashtable_entry -> wg_peer
    struct noise_keypair *kp = BPF_CORE_READ(cb, keypair);
    if (!kp) return 0;

    struct wg_peer *peer = BPF_CORE_READ(kp, entry.peer);
    if (!peer) return 0;

    // get the public key of the peer
    BPF_CORE_READ_INTO(&scratch->pk.key, peer, handshake.remote_static);

#ifdef ENABLE_DOS_PROTECTION
    ///// rate limiting logic /////
    // token bucket
    struct peer_quota *quota = bpf_map_lookup_elem(&map_peer_quotas, &scratch->pk);
    if (!quota) {
        struct peer_quota new_q = { .last_event_ts = now, .tokens = RATE_LIMIT_TOKENS };
        bpf_map_update_elem(&map_peer_quotas, &scratch->pk, &new_q, BPF_ANY);
        quota = bpf_map_lookup_elem(&map_peer_quotas, &scratch->pk);
    }
    if (!quota) return 0;

    bool updated = false;
    #pragma unroll
    for (int i = 0; i < 5; i++) {
        __u64 old_tokens = quota->tokens;
        __u64 last_ts = quota->last_event_ts;
        __u64 new_tokens = old_tokens;

        if (now > last_ts) {
            __u64 elapsed = now - last_ts;
            new_tokens += (elapsed * RATE_LIMIT_TOKENS) / RATE_LIMIT_WINDOW_NS;
            if (new_tokens > RATE_LIMIT_TOKENS) new_tokens = RATE_LIMIT_TOKENS;
        }

        if (new_tokens == 0) return 0;

        new_tokens--;
        if (__sync_bool_compare_and_swap(&quota->tokens, old_tokens, new_tokens)) {
            quota->last_event_ts = now;
            updated = true;
            break;
        }
    }

    if (!updated) return 0;
    ///// end of rate limiting logic ////

    ///// max ips per user limit /////

    // todo: limit concurrent ips, ditch lru if overflow

    //// end of max ips per user limit ////
#endif

    // update ledger
    scratch->record.last_seen = now;
    __builtin_memcpy(scratch->record.public_key, scratch->pk.key, sizeof(scratch->record.public_key));
    
    // notify userspace, which will update wg allowed-ips list
    if (bpf_map_update_elem(&ip_ledger, &saddr, &scratch->record, BPF_NOEXIST) == 0) {
        scratch->event.new_ip = saddr;
        __builtin_memcpy(scratch->event.peer_id, scratch->pk.key, sizeof(scratch->event.peer_id));
        bpf_perf_event_output(ctx, &events, BPF_F_CURRENT_CPU, &scratch->event, sizeof(scratch->event));
    }

    return 0;
}
