/*
Copyright (C) 2026  richardaburton@gmail.com 

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program.  If not, see <http://www.gnu.org/licenses/>.
*/
#include <stdio.h>
#include <signal.h>
#include <unistd.h>
#include <stdint.h>
#include <pthread.h>
#include <time.h>
#include <arpa/inet.h>
#include <bpf/bpf.h>
#include <linux/genetlink.h>
#include <linux/wireguard.h>
#include <libmnl/libmnl.h>

#include "provisioner.h"
#include "provisioner.skel.h" // generated by Makefile

static volatile bool stop = false;
static int family_id = -1;

void handle_sig(int sig) { stop = true; }

static char target_iface[16] = "wg1"; // default interface
static unsigned long long expiry_ns = 86400000000000ULL; // default 24h
static int cleanup_interval_sec = 3600;                  // default 1h

// simplied base64 encoder for 32-byte public keys
static void base64_encode(const unsigned char *src, char *dst) {
    static const char table[] = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/";
    int i, j;
    for (i = 0, j = 0; i < 30; i += 3) {
        dst[j++] = table[src[i] >> 2];
        dst[j++] = table[((src[i] & 3) << 4) | (src[i + 1] >> 4)];
        dst[j++] = table[((src[i + 1] & 15) << 2) | (src[i + 2] >> 6)];
        dst[j++] = table[src[i + 2] & 63];
    }
    // Handle the remaining 2 bytes of the 32-byte key to add correct padding
    dst[j++] = table[src[30] >> 2];
    dst[j++] = table[((src[30] & 3) << 4) | (src[31] >> 4)];
    dst[j++] = table[(src[31] & 15) << 2];
    dst[j++] = '=';
    dst[j] = '\0';
}


// very simple ini reader
static void load_config() {
    FILE *f = fopen("/etc/wg-slaacer.conf", "r");
    if (!f) return;
    char line[128];
    while (fgets(line, sizeof(line), f)) {
        int val;
        if (sscanf(line, "Interface=%15s", target_iface) == 1) {
            continue;
        } else if (sscanf(line, "IPAddrTimeout=%d", &val) == 1) {
            // convert from hours
            expiry_ns = (unsigned long long)val * 3600ULL * 1000000000ULL;
        } else if (sscanf(line, "Cleanup=%d", &val) == 1) {
            // convert from minutes
            cleanup_interval_sec = val * 60;
        }
    }
    fclose(f);
}

struct family_data {
    const char *name;
    uint16_t id;
};

static int family_handler(const struct nlmsghdr *nlh, void *data) {
    struct family_data *f = data;
    struct genlmsghdr *ghdr = mnl_nlmsg_get_payload(nlh);
    struct nlattr *attr;

    // Use the macro to safely iterate over attributes
    mnl_attr_for_each(attr, nlh, sizeof(*ghdr)) {
        uint16_t type = mnl_attr_get_type(attr);

        if (type == CTRL_ATTR_FAMILY_NAME) {
            if (strcmp(mnl_attr_get_str(attr), f->name) != 0)
                return MNL_CB_OK; // Not the family we're looking for
        }

        if (type == CTRL_ATTR_FAMILY_ID) {
            f->id = mnl_attr_get_u16(attr);
        }
    }

    return MNL_CB_OK;
}

static int get_wg_family_id() {
    char buf[MNL_SOCKET_BUFFER_SIZE];
    struct mnl_socket *nl;
    struct nlmsghdr *nlh;
    struct genlmsghdr *ghdr;
    struct family_data f = { .name = WG_GENL_NAME, .id = 0 };
    
    nl = mnl_socket_open(NETLINK_GENERIC);
    if (!nl) return -1;
    if (mnl_socket_bind(nl, 0, MNL_SOCKET_AUTOPID) < 0) goto out;

    nlh = mnl_nlmsg_put_header(buf);
    nlh->nlmsg_type = GENL_ID_CTRL;
    nlh->nlmsg_flags = NLM_F_REQUEST | NLM_F_ACK;
    ghdr = mnl_nlmsg_put_extra_header(nlh, sizeof(struct genlmsghdr));
    ghdr->cmd = CTRL_CMD_GETFAMILY;
    ghdr->version = 2;
    mnl_attr_put_strz(nlh, CTRL_ATTR_FAMILY_NAME, WG_GENL_NAME);

    if (mnl_socket_sendto(nl, nlh, nlh->nlmsg_len) < 0) goto out;

    int ret = mnl_socket_recvfrom(nl, buf, sizeof(buf));
    while (ret > 0) {
        if (mnl_cb_run(buf, ret, 0, mnl_socket_get_portid(nl), family_handler, &f) <= 0)
            break;
        ret = mnl_socket_recvfrom(nl, buf, sizeof(buf));
    }

out:
    mnl_socket_close(nl);
    return f.id > 0 ? f.id : -1;
}

static int wg_mod_allowedip(const char *ifname, const uint8_t public_key[32], const struct in6_addr *addr, bool add) {
    char buf[MNL_SOCKET_BUFFER_SIZE];
    struct nlmsghdr *nlh;
    struct genlmsghdr *ghdr;
    struct mnl_socket *nl;
    int ret = -1;
    unsigned int seq = time(NULL);

    nl = mnl_socket_open(NETLINK_GENERIC);
    if (!nl) return -1;
    if (mnl_socket_bind(nl, 0, MNL_SOCKET_AUTOPID) < 0) goto out;

    nlh = mnl_nlmsg_put_header(buf);
    nlh->nlmsg_type = family_id; 
    nlh->nlmsg_flags = NLM_F_REQUEST | NLM_F_ACK;
    nlh->nlmsg_seq = seq;

    ghdr = mnl_nlmsg_put_extra_header(nlh, sizeof(struct genlmsghdr));
    ghdr->cmd = WG_CMD_SET_DEVICE;
    ghdr->version = 1;

    mnl_attr_put_strz(nlh, WGDEVICE_A_IFNAME, ifname);

    struct nlattr *peers_nest = mnl_attr_nest_start(nlh, WGDEVICE_A_PEERS);
    struct nlattr *peer_nest = mnl_attr_nest_start(nlh, 0); 
    mnl_attr_put(nlh, WGPEER_A_PUBLIC_KEY, 32, public_key);

    struct nlattr *aips_nest = mnl_attr_nest_start(nlh, WGPEER_A_ALLOWEDIPS);
    struct nlattr *aip_nest = mnl_attr_nest_start(nlh, 0);
    
    mnl_attr_put_u16(nlh, WGALLOWEDIP_A_FAMILY, AF_INET6);
    mnl_attr_put(nlh, WGALLOWEDIP_A_IPADDR, 16, addr);
    mnl_attr_put_u8(nlh, WGALLOWEDIP_A_CIDR_MASK, 128);
    
    if (!add) {
        mnl_attr_put_u32(nlh, WGALLOWEDIP_A_FLAGS, WGPEER_F_REMOVE_ME); 
    }

    mnl_attr_nest_end(nlh, aip_nest);
    mnl_attr_nest_end(nlh, aips_nest);
    mnl_attr_nest_end(nlh, peer_nest);
    mnl_attr_nest_end(nlh, peers_nest);

    if (mnl_socket_sendto(nl, nlh, nlh->nlmsg_len) < 0) goto out;

    ret = mnl_socket_recvfrom(nl, buf, sizeof(buf));
    if (ret > 0) {
        ret = mnl_cb_run(buf, ret, seq, mnl_socket_get_portid(nl), NULL, NULL);
    }

out:
    mnl_socket_close(nl);
    return ret;
}

void *cleanup_thread(void *arg) {
    struct provisioner_bpf *skel = (struct provisioner_bpf *)arg;
    int map_fd = bpf_map__fd(skel->maps.ip_ledger);
    struct record_t value;
    struct timespec ts;

    while (!stop) {
        sleep(cleanup_interval_sec);
        if (stop) break;
        struct in6_addr key = {}, next_key;
        clock_gettime(CLOCK_MONOTONIC_COARSE, &ts);
        unsigned long long now = ts.tv_sec * 1000000000ULL + ts.tv_nsec;

        while (bpf_map_get_next_key(map_fd, &key, &next_key) == 0) {
            if (bpf_map_lookup_elem(map_fd, &next_key, &value) == 0) {
                if (now - value.last_seen > expiry_ns) {
                    bpf_map_delete_elem(map_fd, &next_key);
                    
                    char peer_id_b64[45]; // 32 bytes -> 44 chars + null terminator
                    base64_encode(value.public_key, peer_id_b64);
                    char addr_str[INET6_ADDRSTRLEN];
                    inet_ntop(AF_INET6, &next_key, addr_str, sizeof(addr_str));
                    if (wg_mod_allowedip(target_iface, value.public_key, &next_key, false) >= 0) {
                        printf("- %s %s\n", peer_id_b64, addr_str);
                    } else {
                        fprintf(stderr, "Error: - %s %s (%s)\n", peer_id_b64, addr_str, strerror(errno));
                    }
                }
            }
            key = next_key;
        }
        fflush(stdout);
        fflush(stderr);
    }
    return NULL;
}

void handle_event(void *ctx, int cpu, void *data, __u32 size) {
    struct event_t *r = data;
    struct in6_addr addr;
    
    if (r->new_ip == 0) return;
    memcpy(&addr, &r->new_ip, 16);

    char peer_id_b64[45]; // 32 bytes -> 44 chars + null terminator
    base64_encode(r->peer_id, peer_id_b64);
    char addr_str[INET6_ADDRSTRLEN];
    inet_ntop(AF_INET6, &addr, addr_str, sizeof(addr_str));

    if (wg_mod_allowedip(target_iface, r->peer_id, &addr, true) >= 0) {
        printf("+ %s %s\n", peer_id_b64, addr_str);
        fflush(stdout);
    } else {
        fprintf(stderr, "Error: + %s %s (%s)\n", peer_id_b64, addr_str, strerror(errno));
        fflush(stderr);
    }
}

int main() {
    load_config();
    printf("Starting provisioner on interface: %s\n", target_iface);
    fflush(stdout);

    family_id = get_wg_family_id();
    if (family_id < 0) return 1;
    //printf("family_id: %d\n", family_id);

    struct provisioner_bpf *skel = provisioner_bpf__open();
    if (!skel) {
        fprintf(stderr, "Failed to open BPF skeleton\n");
        return 1;
    }

    // pass the interface name to bpf program via rodata
    strncpy(skel->rodata->target_ifname, target_iface, 16);

    if (provisioner_bpf__load(skel)) {
        fprintf(stderr, "Failed to load BPF skeleton\n");
        return 1;
    }

    if (provisioner_bpf__attach(skel)) {
        fprintf(stderr, "Failed to attach BPF skeleton\n");
        return 1;
    }

    struct perf_buffer *pb = perf_buffer__new(bpf_map__fd(skel->maps.events), 8, handle_event, NULL, NULL, NULL);
    if (!pb) {
        fprintf(stderr, "Failed to create perf buffer\n");
        return 1;
    }

	pthread_t tid;
    if (pthread_create(&tid, NULL, cleanup_thread, skel) != 0) {
        fprintf(stderr, "Failed to create cleanup thread\n");
        return 1;
    }

    // Main loop for perf events
    while (!stop) {
        perf_buffer__poll(pb, 100);
    }

    pthread_join(tid, NULL);
    provisioner_bpf__destroy(skel);
    return 0;
}
