# the parser is very simple, you must follow the format exactly with no extra spaces, case sensitive key name
# (e.g. Interface = wg1 will not work, it must be Interface=wg1 )
[Settings]

# The WireGuard interface to monitor (e.g. wg0, wg1, etc.)
#Interface=wg1

# The duration (in hours), since last known use, after which an IP address is considered expired and can be removed
#IPAddrTimeout=24

# The interval (in minutes) at which cleanup operations are performed
#Cleanup=60
